version: '3.8'
volumes:
  data:
  test_data:

services:
  postgres:
    image: postgres:15.3
    container_name: db
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
  test_db:
    image: postgres:15.3
    container_name: test_db
    volumes:
      - test_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME_TEST}
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASS_TEST}
  web:
    build: ./
    container_name: cablock
    ports:
      - '8080:80'
    env_file:
      - .env
    depends_on:
      - postgres
      - test_db
